import type { Product } from './types';

// Static catalog used to seed the database and as fallback if DB is unreachable.
// Images are high-quality beauty/cosmetics photography from Pexels.
export const STATIC_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Velvet Matte Lipstick — Rose Petal',
    category: 'Makeup',
    price: 38,
    old_price: 48,
    rating: 4.9,
    reviews: 1240,
    badge: 'Sale',
    discount: 21,
    image: 'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/264819/pexels-photo-264819.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A luxurious matte lipstick with a creamy, long-wearing formula that delivers intense color in a single swipe. Infused with vitamin E and rose oil for comfortable, hydrated wear.',
    is_active: true,
    created_at: '2025-01-15T00:00:00Z',
  },
  {
    id: 'p2',
    name: 'Luminous Silk Foundation',
    category: 'Makeup',
    price: 54,
    old_price: null,
    rating: 4.8,
    reviews: 890,
    badge: 'New',
    discount: 0,
    image: 'https://images.pexels.com/photos/2253833/pexels-photo-2253833.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/2113855/pexels-photo-2113855.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A weightless, buildable foundation that blends seamlessly for a radiant, natural finish. Formulated with hyaluronic acid for all-day hydration and a luminous glow.',
    is_active: true,
    created_at: '2025-02-20T00:00:00Z',
  },
  {
    id: 'p3',
    name: 'Golden Hour Eyeshadow Palette',
    category: 'Makeup',
    price: 62,
    old_price: 75,
    rating: 5.0,
    reviews: 2100,
    badge: 'Trending',
    discount: 17,
    image: 'https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/2623948/pexels-photo-2623948.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A 12-shade palette of buttery-soft neutrals and warm metallics inspired by golden hour light. Highly pigmented, blendable, and crease-resistant for up to 12 hours.',
    is_active: true,
    created_at: '2025-01-10T00:00:00Z',
  },
  {
    id: 'p4',
    name: 'Petal Glow Blush Compact',
    category: 'Makeup',
    price: 34,
    old_price: null,
    rating: 4.7,
    reviews: 560,
    badge: null,
    discount: 0,
    image: 'https://images.pexels.com/photos/2532576/pexels-photo-2532576.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A silky-powder blush that sweeps on a natural, lit-from-within flush. Buildable color with a soft-matte finish that lasts all day without looking dry.',
    is_active: true,
    created_at: '2025-03-01T00:00:00Z',
  },
  {
    id: 'p5',
    name: 'Champagne Highlighter Drops',
    category: 'Makeup',
    price: 42,
    old_price: 52,
    rating: 4.9,
    reviews: 780,
    badge: 'Sale',
    discount: 19,
    image: 'https://images.pexels.com/photos/2532578/pexels-photo-2532578.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/3373745/pexels-photo-3373745.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Liquid highlighter drops that deliver an ethereal, champagne glow. Mix with foundation or apply to cheekbones for a radiant, lit-from-within luminosity.',
    is_active: true,
    created_at: '2025-02-05T00:00:00Z',
  },
  {
    id: 'p6',
    name: 'Flawless Full Coverage Concealer',
    category: 'Makeup',
    price: 29,
    old_price: null,
    rating: 4.6,
    reviews: 430,
    badge: null,
    discount: 0,
    image: 'https://images.pexels.com/photos/2532580/pexels-photo-2532580.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/3373738/pexels-photo-3373738.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A crease-resistant, full-coverage concealer that hides blemishes, dark circles, and redness. Lightweight formula with a natural-matte finish that never settles.',
    is_active: true,
    created_at: '2025-01-25T00:00:00Z',
  },
  {
    id: 'p7',
    name: 'Volume Lift Mascara — Onyx',
    category: 'Makeup',
    price: 26,
    old_price: null,
    rating: 4.8,
    reviews: 1560,
    badge: 'Best Seller',
    discount: 0,
    image: 'https://images.pexels.com/photos/2532584/pexels-photo-2532584.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/3373741/pexels-photo-3373741.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A volumizing and lifting mascara that coats every lash for dramatic, fanned-out volume. Smudge-proof and flake-free formula that washes off easily with warm water.',
    is_active: true,
    created_at: '2025-02-12T00:00:00Z',
  },
  {
    id: 'p8',
    name: 'Precision Liquid Eyeliner',
    category: 'Makeup',
    price: 24,
    old_price: null,
    rating: 4.7,
    reviews: 620,
    badge: null,
    discount: 0,
    image: 'https://images.pexels.com/photos/2532585/pexels-photo-2532585.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/3373743/pexels-photo-3373743.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A felt-tip liquid eyeliner with an ultra-fine tip for precise, bold lines. Intense black pigment glides on smoothly and stays put for up to 16 hours.',
    is_active: true,
    created_at: '2025-03-05T00:00:00Z',
  },
  {
    id: 'p9',
    name: 'Radiance Renewal Serum',
    category: 'Skincare',
    price: 78,
    old_price: 95,
    rating: 4.9,
    reviews: 1890,
    badge: 'Sale',
    discount: 18,
    image: 'https://images.pexels.com/photos/3018845/pexels-photo-3018845.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/3762875/pexels-photo-3762875.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A potent vitamin C and hyaluronic acid serum that brightens, firms, and deeply hydrates. Visibly reduces dark spots and fine lines for a radiant, youthful complexion.',
    is_active: true,
    created_at: '2025-01-08T00:00:00Z',
  },
  {
    id: 'p10',
    name: 'Hydra-Luxe Moisturizer',
    category: 'Skincare',
    price: 56,
    old_price: null,
    rating: 4.8,
    reviews: 940,
    badge: 'New',
    discount: 0,
    image: 'https://images.pexels.com/photos/4202925/pexels-photo-4202925.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/4202924/pexels-photo-4202924.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A rich, whipped moisturizer that delivers 48-hour hydration with ceramides and squalane. Leaves skin plump, soft, and dewy without any greasy residue.',
    is_active: true,
    created_at: '2025-02-28T00:00:00Z',
  },
  {
    id: 'p11',
    name: 'Rose Quartz Sheet Mask Set',
    category: 'Skincare',
    price: 32,
    old_price: null,
    rating: 4.7,
    reviews: 410,
    badge: null,
    discount: 0,
    image: 'https://images.pexels.com/photos/4202926/pexels-photo-4202926.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/4202325/pexels-photo-4202325.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A set of five bio-cellulose sheet masks infused with rose quartz extract and peptides. Drenches skin in moisture for a glowing, refreshed complexion in 15 minutes.',
    is_active: true,
    created_at: '2025-03-10T00:00:00Z',
  },
  {
    id: 'p12',
    name: 'Silk Shield SPF 50 Sunscreen',
    category: 'Skincare',
    price: 44,
    old_price: null,
    rating: 4.9,
    reviews: 1120,
    badge: 'Best Seller',
    discount: 0,
    image: 'https://images.pexels.com/photos/4202927/pexels-photo-4202927.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A weightless, invisible SPF 50 sunscreen with a silky finish. Protects against UVA/UVB and blue light while niacinamide evens skin tone. No white cast.',
    is_active: true,
    created_at: '2025-01-18T00:00:00Z',
  },
  {
    id: 'p13',
    name: 'Pro Rose Gold Brush Set (12 pc)',
    category: 'Accessories',
    price: 89,
    old_price: 120,
    rating: 5.0,
    reviews: 670,
    badge: 'Limited Edition',
    discount: 26,
    image: 'https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/2623948/pexels-photo-2623948.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A 12-piece professional brush set with ultra-soft synthetic bristles and rose gold ferrules. Includes a luxe vegan leather case for storage and travel.',
    is_active: true,
    created_at: '2025-02-15T00:00:00Z',
  },
  {
    id: 'p14',
    name: 'Cloud Soft Beauty Blender Duo',
    category: 'Accessories',
    price: 18,
    old_price: null,
    rating: 4.6,
    reviews: 380,
    badge: null,
    discount: 0,
    image: 'https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/3373745/pexels-photo-3373745.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A duo of latex-free beauty sponges that expand when wet for a flawless, airbrushed finish. Edgeless design blends foundation, concealer, and cream products seamlessly.',
    is_active: true,
    created_at: '2025-03-08T00:00:00Z',
  },
  {
    id: 'p15',
    name: 'Luxe LED Vanity Mirror',
    category: 'Accessories',
    price: 145,
    old_price: null,
    rating: 4.9,
    reviews: 290,
    badge: "Editor's Pick",
    discount: 0,
    image: 'https://images.pexels.com/photos/3997383/pexels-photo-3997383.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/3997385/pexels-photo-3997385.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A Hollywood-style LED vanity mirror with adjustable lighting and 10x magnification. Touch-sensor dimming and a USB port for charging while you glam.',
    is_active: true,
    created_at: '2025-01-30T00:00:00Z',
  },
  {
    id: 'p16',
    name: 'Midnight Rose Eau de Parfum',
    category: 'Fragrances',
    price: 128,
    old_price: 155,
    rating: 5.0,
    reviews: 1450,
    badge: 'Sale',
    discount: 17,
    image: 'https://images.pexels.com/photos/1961795/pexels-photo-1961795.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/1961796/pexels-photo-1961796.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'An intoxicating floral-oriental fragrance with notes of Bulgarian rose, oud, and warm amber. Long-lasting sillage in a sculpted glass flacon with a gold cap.',
    is_active: true,
    created_at: '2025-02-01T00:00:00Z',
  },
  {
    id: 'p17',
    name: 'Gardenia Blossom Perfume',
    category: 'Fragrances',
    price: 95,
    old_price: null,
    rating: 4.8,
    reviews: 520,
    badge: 'New',
    discount: 0,
    image: 'https://images.pexels.com/photos/264819/pexels-photo-264819.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/264820/pexels-photo-264820.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A fresh, luminous floral fragrance with gardenia, jasmine, and white musk. Captures the essence of a blooming garden in an elegant frosted-glass bottle.',
    is_active: true,
    created_at: '2025-03-12T00:00:00Z',
  },
  {
    id: 'p18',
    name: 'Velvet Nourishing Lip Oil',
    category: 'Makeup',
    price: 22,
    old_price: null,
    rating: 4.7,
    reviews: 340,
    badge: 'New',
    discount: 0,
    image: 'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/264819/pexels-photo-264819.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A nourishing lip oil that delivers a glass-like shine with a hint of color. Infused with jojoba and rosehip oils for soft, hydrated, plump lips.',
    is_active: true,
    created_at: '2025-03-15T00:00:00Z',
  },
  {
    id: 'p19',
    name: 'Retinol Night Renewal Cream',
    category: 'Skincare',
    price: 68,
    old_price: 82,
    rating: 4.9,
    reviews: 870,
    badge: 'Trending',
    discount: 17,
    image: 'https://images.pexels.com/photos/4202925/pexels-photo-4202925.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/3762875/pexels-photo-3762875.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A gentle 0.3% retinol night cream that smooths fine lines and boosts collagen. Encapsulated retinol releases slowly to minimize irritation while you sleep.',
    is_active: true,
    created_at: '2025-02-22T00:00:00Z',
  },
  {
    id: 'p20',
    name: 'Amber Oud Extrait de Parfum',
    category: 'Fragrances',
    price: 185,
    old_price: null,
    rating: 5.0,
    reviews: 380,
    badge: "Editor's Pick",
    discount: 0,
    image: 'https://images.pexels.com/photos/1961795/pexels-photo-1961795.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos-1961796/pexels-photo-1961796.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A luxurious extrait de parfum with rich amber, oud, and saffron. Exceptional longevity and depth in a hand-finished crystal flacon with a gold-plated cap.',
    is_active: true,
    created_at: '2025-01-05T00:00:00Z',
  },
  {
    id: 'p21',
    name: 'Pearl Glow Setting Powder',
    category: 'Makeup',
    price: 36,
    old_price: null,
    rating: 4.8,
    reviews: 610,
    badge: null,
    discount: 0,
    image: 'https://images.pexels.com/photos/2532576/pexels-photo-2532576.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A finely milled setting powder with a soft-focus pearl finish. Sets makeup while adding a subtle, luminous glow that never looks chalky or dry.',
    is_active: true,
    created_at: '2025-03-02T00:00:00Z',
  },
  {
    id: 'p22',
    name: 'Sculpt & Glow Contour Trio',
    category: 'Makeup',
    price: 48,
    old_price: 58,
    rating: 4.7,
    reviews: 450,
    badge: 'Sale',
    discount: 17,
    image: 'https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=800',
    hover_image: 'https://images.pexels.com/photos-2623948/pexels-photo-2623948.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A three-pan contour, bronzer, and highlighter palette for sculpted, dimensional skin. Matte and shimmer finishes in blendable, buildable powders.',
    is_active: true,
    created_at: '2025-02-18T00:00:00Z',
  },
];

export const CATEGORIES = [
  { name: 'Makeup', subcategories: ['Lipsticks', 'Foundations', 'Eyeshadow', 'Blush', 'Highlighters', 'Concealers', 'Mascaras', 'Eyeliners'] },
  { name: 'Skincare', subcategories: ['Serums', 'Moisturizers', 'Face Masks', 'Sunscreen'] },
  { name: 'Accessories', subcategories: ['Brush Sets', 'Beauty Blenders', 'Mirrors'] },
  { name: 'Fragrances', subcategories: ['Eau de Parfum', 'Extrait de Parfum'] },
];

export const TESTIMONIALS = [
  {
    name: 'Isabella Moreau',
    location: 'Paris, France',
    rating: 5,
    review: 'ANISBEAUTY has completely transformed my beauty routine. The Velvet Matte Lipstick lasts all day without drying my lips, and the shade range is stunning. I feel confident every time I wear it.',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    name: 'Sophia Chen',
    location: 'New York, USA',
    rating: 5,
    review: 'The Radiance Renewal Serum is pure magic. My dark spots have faded and my skin looks so much brighter. The packaging feels so luxurious — it is like a spa experience at home.',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    name: 'Amara Okafor',
    location: 'London, UK',
    rating: 5,
    review: 'I am obsessed with the Golden Hour Palette. The pigmentation is incredible and the shades blend like a dream. This is the only palette I reach for now. Worth every penny.',
    avatar: 'https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    name: 'Priya Sharma',
    location: 'Mumbai, India',
    rating: 5,
    review: 'The Midnight Rose perfume is the most beautiful scent I have ever worn. I get compliments everywhere I go. Long-lasting and so elegant. ANISBEAUTY never disappoints.',
    avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    name: 'Elena Rossi',
    location: 'Milan, Italy',
    rating: 5,
    review: 'The Hydra-Luxe Moisturizer saved my dry winter skin. It is rich but not greasy and my skin looks plump and glowing. The rose gold packaging on my vanity is gorgeous.',
    avatar: 'https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
];
